class extra():
	b = ''
	b_close = ''
	u = ''
	color_white = '0'
	color_black = '1'
	color_darkBlue = '2'
	color_darkGreen = '3'
	color_red = '4'
	color_darkRed = '5'
	color_purple = '6'
	color_orange = '7'
	color_yellow = '8'
	color_lightGreen = '9'
	color_turquoise = '10'
	color_lightBlue = '12'
	color_pink = '13'
	color_darkGray = '14'
	color_gray = '15'
def run(text,sock):pass